In [1]:
from __future__ import division
import pandas as pd
import numpy as np
loans = pd.read_csv("../data/lending-club-data.csv")

/home/chaitanya/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (19,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [30]:
loans.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'is_inc_v', 'issue_d',
       'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title',
       'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'not_compliant', 'status', 'inactive_loans', 'bad_loans',
       'emp_length_num', 'grade_num', 'sub_gra

In [31]:
# safe_loans =  1 => safe
# safe_loans = -1 => risky
loans['safe_loans'] = loans['bad_loans'].apply(lambda x : +1 if x==0 else -1)
loans = loans.drop('bad_loans',axis = 1)

In [32]:
sum(loans['safe_loans'].apply(lambda x : 1 if x == +1 else 0 ))/len(loans['safe_loans'])

0.81118533199572618

In [33]:
features = ['grade',                     # grade of the loan
            'sub_grade',                 # sub-grade of the loan
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'term',                      # the term of the loan
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
           ]

target = 'safe_loans'                    # prediction target (y) (+1 means safe, -1 is risky)

# Extract the feature columns and target column
loans = loans[features + [target]]

In [34]:
loans = pd.get_dummies(loans)

In [36]:
import json
with open("module-5-assignment-1-train-idx.json") as f :
    train_idx = json.load(f)
with open("module-5-assignment-1-validation-idx.json") as f:
    validation_idx = json.load(f)
train_data = loans.iloc[train_idx]
validation_data = loans.iloc[validation_idx]

In [37]:
train_target = train_data['safe_loans']
train_features_data = train_data.drop('safe_loans',axis = 1) 

In [38]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_model = DecisionTreeClassifier(max_depth = 6)
decision_tree_model.fit(train_features_data,train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=6,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [51]:
small_model = DecisionTreeClassifier(max_depth = 2)
small_model.fit(train_features_data,train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [52]:
from sklearn.tree import export_graphviz
export_graphviz(small_model,'small_model.dot')

In [53]:
validation_safe_loans = validation_data[validation_data[target] == 1]
validation_risky_loans = validation_data[validation_data[target] == -1]

sample_validation_data_risky = validation_risky_loans[0:2]
sample_validation_data_safe = validation_safe_loans[0:2]

sample_validation_data = sample_validation_data_safe.append(sample_validation_data_risky)
sample_validation_data

short_emp  emp_length_num    dti  last_delinq_none  last_major_derog_none  \
19          0              11  11.18                 1                      1   
79          0              10  16.85                 1                      1   
24          0               3  13.97                 0                      1   
41          0              11  16.33                 1                      1   

    revol_util  total_rec_late_fee  safe_loans  grade_A  grade_B  \
19        82.4                 0.0           1      0.0      1.0   
79        96.4                 0.0           1      0.0      0.0   
24        59.5                 0.0          -1      0.0      0.0   
41        62.1                 0.0          -1      1.0      0.0   

         ...         purpose_house  purpose_major_purchase  purpose_medical  \
19       ...                   0.0                     0.0              0.0   
79       ...                   0.0                     0.0              0.0   
24       ...                   0.0                     0.0              0.0   
41       ...                   0.0                     0.0              0.0   

    purpose_moving  purpose_other  purpose_small_business  purpose_vacation  \
19             0.0            0.0                     0.0               0.0   
79             0.0            0.0                     0.0               0.0   
24             0.0            1.0                     0.0               0.0   
41             0.0            0.0                     0.0               0.0   

    purpose_wedding  term_ 36 months  term_ 60 months  
19              0.0              1.0              0.0  
79              0.0              1.0              0.0  
24              0.0              0.0              1.0  
41              0.0              1.0              0.0  

[4 rows x 68 columns]

In [54]:
sample_features = sample_validation_data.drop('safe_loans',axis = 1)
print(decision_tree_model.predict(sample_features))
print(decision_tree_model.score(sample_features,sample_validation_data['safe_loans']))

[ 1 -1 -1  1]
0.5


In [55]:
print(decision_tree_model.predict_proba(sample_features))

[[ 0.34156543  0.65843457]
 [ 0.53630646  0.46369354]
 [ 0.64750958  0.35249042]
 [ 0.20789474  0.79210526]]


In [56]:
print(small_model.predict_proba(sample_features))

[[ 0.41896585  0.58103415]
 [ 0.59255339  0.40744661]
 [ 0.59255339  0.40744661]
 [ 0.23120112  0.76879888]]


In [50]:
sample_validation_data.iloc[1]

short_emp                      0.00
emp_length_num                10.00
dti                           16.85
last_delinq_none               1.00
last_major_derog_none          1.00
revol_util                    96.40
total_rec_late_fee             0.00
safe_loans                     1.00
grade_A                        0.00
grade_B                        0.00
grade_C                        0.00
grade_D                        1.00
grade_E                        0.00
grade_F                        0.00
grade_G                        0.00
sub_grade_A1                   0.00
sub_grade_A2                   0.00
sub_grade_A3                   0.00
sub_grade_A4                   0.00
sub_grade_A5                   0.00
sub_grade_B1                   0.00
sub_grade_B2                   0.00
sub_grade_B3                   0.00
sub_grade_B4                   0.00
sub_grade_B5                   0.00
sub_grade_C1                   0.00
sub_grade_C2                   0.00
sub_grade_C3                

In [57]:
print(decision_tree_model.score(train_features_data,train_target))
print(small_model.score(train_features_data,train_target))

0.640527616591
0.613502041694


In [58]:
validation_target = validation_data['safe_loans']
validation_features_data = validation_data.drop('safe_loans',axis = 1) 
print(decision_tree_model.score(validation_features_data,validation_target))
print(small_model.score(validation_features_data,validation_target))

0.636148211978
0.619345109866


In [59]:
big_model = DecisionTreeClassifier(max_depth = 10)
big_model.fit(train_features_data,train_target)
print(big_model.score(train_features_data,train_target))
print(big_model.score(validation_features_data,validation_target))

0.663738448313
0.626023265834


In [60]:
from sklearn.metrics import confusion_matrix
pred = decision_tree_model.predict(validation_features_data)
confusion_matrix(validation_target,pred)

array([[3013, 1661],
       [1717, 2893]])